language: python
python:
  - "3.6"
install:
  - python setup.py install
  - pip install coveralls
script:
  - coverage run setup.py test
after_success:
  coveralls
notifications:
  email:
    - ci-notify@openlabs.co.in
